"""create User model

Revision ID: 0b1519da780d
Revises: 
Create Date: 2025-08-11 18:03:54.839859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1519da780d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('имя', sa.String(length=120), nullable=False),
    sa.Column('фамилия', sa.String(length=120), nullable=False),
    sa.Column('отчество', sa.String(length=120), nullable=False),
    sa.Column('эл_почта', sa.String(length=100), nullable=False),
    sa.Column('пароль', sa.Text(), nullable=False),
    sa.Column('активный', sa.Boolean(), nullable=False),
    sa.Column('подтверждён', sa.Boolean(), nullable=False),
    sa.Column('админ', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('эл_почта')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
